#:schema node_modules/wrangler/config-schema.json
name = "illustratewords"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "illustratewords-sponsors"
database_id = "1919fc53-bac2-4ed0-b967-1588db2b8a1b"
